#!/bin/bash


echo	" This will install the Milksteak Package Manager to $HOME/usr."
read -p " Do you wish to continue? (y/n) " -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
fi

echo "Installing Milksteak..."
echo
git clone https://github.com/milksteak-project/Milksteak.git $HOME/usr
ln -s $HOME/usr/libexec/steak $HOME/usr/bin/steak
mkdir $HOME/usr/share/bpm
mv $HOME/usr/LICENSE $HOME/usr/share/bpm/LICENSE
mkdir $HOME/usr/share/milksteak
mv $HOME/usr/README.md $HOME/usr/share/milksteak/README.md
mv $HOME/usr/milksteak.png $HOME/usr/share/milksteak/milksteak.png
chflags hidden $HOME/usr
cat <<EOT >> $HOME/.bash_profile


export PATH=$HOME/usr/bin:$HOME/usr/sbin:$PATH

EOT
$HOME/usr/bin/steak install tiv
tiv $HOME/usr/share/milksteak/milksteak.png
echo
echo 	" Milksteak v0.0.1 has been successfully installed to $HOME/usr."
echo	" Type 'steak help' for more info."
