#!/bin/bash
# Usage: steak install <name>
# Summary: Install a package
set -e

name=$1

rm -rf $HOME/usr/etc/packages/$name
mkdir -p $HOME/usr/etc/packages/$name

pkgdir=$HOME/usr/etc/packages/$name
pkg=$HOME/usr/etc/packages/$name/$name.sh

echo "═══════════════════════════════════════════════════════════════════════════"
echo ">>>>>>>> Downloading installer: $name ..."
wget -O $pkg https://raw.githubusercontent.com/milksteak-project/steaks/master/packages/$name/$name.sh -q --show-progress

/bin/bash $pkgdir/$name.sh
