#!/bin/bash
# Usage: steak install <name>
# Summary: Install a package
set -e

name=$1
mkdir -p $HOME/usr/packages
pkg=$HOME/usr/etc/packages/$name

echo "═══════════════════════════════════════════════════════════════════════════"
echo ">>>>>>>> Downloading installer: $name ..."
wget -O $pkg https://github.com/sigma-1/steaks/blob/master/packages/$name/$name.sh

cd $pkg
/bin/bash $name.sh
cd ..
rm -rf $pkg
