#!/usr/bin/env bash
# Usage: steak uninstall <package-name>
# Summary: Uninstall package

set -e

name=$1

printf '\e[1m%*s\n\e[m' "${COLUMNS:-$(tput cols)}" '' | tr ' ' =
/usr/bin/env bash <(curl -s https://raw.githubusercontent.com/milksteak-project/steaks/master/packages/$name/uninstall.sh)
