#!/usr/bin/env bash
# Usage: steak update
# Summary: Update Milksteak

set -e

function update() {
  git clone https://github.com/milksteak-project/milksteak.git $HOME/usr/tmp/milksteak
  rm -rf $HOME/usr/libexec ; cp -r $HOME/usr/tmp/milksteak/libexec $HOME/usr/libexec
  rm -rf $HOME/usr/tmp/milksteak
}

printf '\e[1m%*s\n\e[m' "${COLUMNS:-$(tput cols)}" '' | tr ' ' =
echo -e ">>>>> Updating Milksteak..."
update &> /dev/null
echo -e "Milksteak has been updated!"
