#!/bin/bash
# Usage: steak update [package name]
# Summary: Update one or all steak packages
set -e

name=$1

function update {
  name=$1
  pkg=$HOME/usr/etc/milksteak/$name

  echo Updating $name
  cd $pkg
  git pull
  bash *.sh
}

if [ $name ]
then
  update $name
else
  for pkg in $HOME/usr/etc/packages/*
  do
    name=`basename $pkg`
    update $name
  done
fi
